apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-almgithub-client-secret
type: Opaque
stringData:
  clientSecret: example-client-secret

---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-almgithub-private-key
type: Opaque
stringData:
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----

---
apiVersion: integration.sonarqube.crossplane.io/v1alpha1
kind: ALMGitHub
metadata:
  namespace: default
  name: example-almgithub
spec:
  forProvider:
    key: github-main
    url: https://api.github.com
    appId: "123456"
    clientId: "Iv1.abc123"
    clientSecretRef:
      name: example-almgithub-client-secret
      key: clientSecret
    privateKeyRef:
      name: example-almgithub-private-key
      key: privateKey
  providerConfigRef:
    name: example
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: example-almgithub-connection
