apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-almazure-token
type: Opaque
stringData:
  token: example
---
apiVersion: integration.sonarqube.crossplane.io/v1alpha1
kind: ALMAzure
metadata:
  namespace: default
  name: example-almazure
spec:
  forProvider:
    key: azure-main
    url: https://dev.azure.com/example
    personalAccessTokenSecretRef:
      name: example-almazure-token
      key: token
  providerConfigRef:
    name: example
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: example-almazure-connection
