apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-almgitlab-token
type: Opaque
stringData:
  token: example
---
apiVersion: integration.sonarqube.crossplane.io/v1alpha1
kind: ALMGitLab
metadata:
  namespace: default
  name: example-almgitlab
spec:
  forProvider:
    key: gitlab-main
    url: https://gitlab.example.com
    personalAccessTokenSecretRef:
      name: example-almgitlab-token
      key: token
  providerConfigRef:
    name: example
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: example-almgitlab-connection
