//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzure) DeepCopyInto(out *ALMAzure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzure.
func (in *ALMAzure) DeepCopy() *ALMAzure {
	if in == nil {
		return nil
	}
	out := new(ALMAzure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMAzure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzureList) DeepCopyInto(out *ALMAzureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALMAzure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzureList.
func (in *ALMAzureList) DeepCopy() *ALMAzureList {
	if in == nil {
		return nil
	}
	out := new(ALMAzureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMAzureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzureObservation) DeepCopyInto(out *ALMAzureObservation) {
	*out = *in
	out.ALMCommonObservation = in.ALMCommonObservation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzureObservation.
func (in *ALMAzureObservation) DeepCopy() *ALMAzureObservation {
	if in == nil {
		return nil
	}
	out := new(ALMAzureObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzureParameters) DeepCopyInto(out *ALMAzureParameters) {
	*out = *in
	in.ALMCommonParameters.DeepCopyInto(&out.ALMCommonParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzureParameters.
func (in *ALMAzureParameters) DeepCopy() *ALMAzureParameters {
	if in == nil {
		return nil
	}
	out := new(ALMAzureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzureSpec) DeepCopyInto(out *ALMAzureSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzureSpec.
func (in *ALMAzureSpec) DeepCopy() *ALMAzureSpec {
	if in == nil {
		return nil
	}
	out := new(ALMAzureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMAzureStatus) DeepCopyInto(out *ALMAzureStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMAzureStatus.
func (in *ALMAzureStatus) DeepCopy() *ALMAzureStatus {
	if in == nil {
		return nil
	}
	out := new(ALMAzureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucket) DeepCopyInto(out *ALMBitbucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucket.
func (in *ALMBitbucket) DeepCopy() *ALMBitbucket {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMBitbucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloud) DeepCopyInto(out *ALMBitbucketCloud) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloud.
func (in *ALMBitbucketCloud) DeepCopy() *ALMBitbucketCloud {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMBitbucketCloud) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloudList) DeepCopyInto(out *ALMBitbucketCloudList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALMBitbucketCloud, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloudList.
func (in *ALMBitbucketCloudList) DeepCopy() *ALMBitbucketCloudList {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloudList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMBitbucketCloudList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloudObservation) DeepCopyInto(out *ALMBitbucketCloudObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloudObservation.
func (in *ALMBitbucketCloudObservation) DeepCopy() *ALMBitbucketCloudObservation {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloudObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloudParameters) DeepCopyInto(out *ALMBitbucketCloudParameters) {
	*out = *in
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloudParameters.
func (in *ALMBitbucketCloudParameters) DeepCopy() *ALMBitbucketCloudParameters {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloudParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloudSpec) DeepCopyInto(out *ALMBitbucketCloudSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloudSpec.
func (in *ALMBitbucketCloudSpec) DeepCopy() *ALMBitbucketCloudSpec {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketCloudStatus) DeepCopyInto(out *ALMBitbucketCloudStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketCloudStatus.
func (in *ALMBitbucketCloudStatus) DeepCopy() *ALMBitbucketCloudStatus {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketCloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketList) DeepCopyInto(out *ALMBitbucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALMBitbucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketList.
func (in *ALMBitbucketList) DeepCopy() *ALMBitbucketList {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMBitbucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketObservation) DeepCopyInto(out *ALMBitbucketObservation) {
	*out = *in
	out.ALMCommonObservation = in.ALMCommonObservation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketObservation.
func (in *ALMBitbucketObservation) DeepCopy() *ALMBitbucketObservation {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketParameters) DeepCopyInto(out *ALMBitbucketParameters) {
	*out = *in
	in.ALMCommonParameters.DeepCopyInto(&out.ALMCommonParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketParameters.
func (in *ALMBitbucketParameters) DeepCopy() *ALMBitbucketParameters {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketSpec) DeepCopyInto(out *ALMBitbucketSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketSpec.
func (in *ALMBitbucketSpec) DeepCopy() *ALMBitbucketSpec {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMBitbucketStatus) DeepCopyInto(out *ALMBitbucketStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMBitbucketStatus.
func (in *ALMBitbucketStatus) DeepCopy() *ALMBitbucketStatus {
	if in == nil {
		return nil
	}
	out := new(ALMBitbucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMCommonObservation) DeepCopyInto(out *ALMCommonObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMCommonObservation.
func (in *ALMCommonObservation) DeepCopy() *ALMCommonObservation {
	if in == nil {
		return nil
	}
	out := new(ALMCommonObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMCommonParameters) DeepCopyInto(out *ALMCommonParameters) {
	*out = *in
	if in.PersonalAccessTokenSecretRef != nil {
		in, out := &in.PersonalAccessTokenSecretRef, &out.PersonalAccessTokenSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMCommonParameters.
func (in *ALMCommonParameters) DeepCopy() *ALMCommonParameters {
	if in == nil {
		return nil
	}
	out := new(ALMCommonParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHub) DeepCopyInto(out *ALMGitHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHub.
func (in *ALMGitHub) DeepCopy() *ALMGitHub {
	if in == nil {
		return nil
	}
	out := new(ALMGitHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMGitHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHubList) DeepCopyInto(out *ALMGitHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALMGitHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHubList.
func (in *ALMGitHubList) DeepCopy() *ALMGitHubList {
	if in == nil {
		return nil
	}
	out := new(ALMGitHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMGitHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHubObservation) DeepCopyInto(out *ALMGitHubObservation) {
	*out = *in
	out.ALMCommonObservation = in.ALMCommonObservation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHubObservation.
func (in *ALMGitHubObservation) DeepCopy() *ALMGitHubObservation {
	if in == nil {
		return nil
	}
	out := new(ALMGitHubObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHubParameters) DeepCopyInto(out *ALMGitHubParameters) {
	*out = *in
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHubParameters.
func (in *ALMGitHubParameters) DeepCopy() *ALMGitHubParameters {
	if in == nil {
		return nil
	}
	out := new(ALMGitHubParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHubSpec) DeepCopyInto(out *ALMGitHubSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHubSpec.
func (in *ALMGitHubSpec) DeepCopy() *ALMGitHubSpec {
	if in == nil {
		return nil
	}
	out := new(ALMGitHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitHubStatus) DeepCopyInto(out *ALMGitHubStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitHubStatus.
func (in *ALMGitHubStatus) DeepCopy() *ALMGitHubStatus {
	if in == nil {
		return nil
	}
	out := new(ALMGitHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLab) DeepCopyInto(out *ALMGitLab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLab.
func (in *ALMGitLab) DeepCopy() *ALMGitLab {
	if in == nil {
		return nil
	}
	out := new(ALMGitLab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMGitLab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLabList) DeepCopyInto(out *ALMGitLabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ALMGitLab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLabList.
func (in *ALMGitLabList) DeepCopy() *ALMGitLabList {
	if in == nil {
		return nil
	}
	out := new(ALMGitLabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ALMGitLabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLabObservation) DeepCopyInto(out *ALMGitLabObservation) {
	*out = *in
	out.ALMCommonObservation = in.ALMCommonObservation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLabObservation.
func (in *ALMGitLabObservation) DeepCopy() *ALMGitLabObservation {
	if in == nil {
		return nil
	}
	out := new(ALMGitLabObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLabParameters) DeepCopyInto(out *ALMGitLabParameters) {
	*out = *in
	in.ALMCommonParameters.DeepCopyInto(&out.ALMCommonParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLabParameters.
func (in *ALMGitLabParameters) DeepCopy() *ALMGitLabParameters {
	if in == nil {
		return nil
	}
	out := new(ALMGitLabParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLabSpec) DeepCopyInto(out *ALMGitLabSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLabSpec.
func (in *ALMGitLabSpec) DeepCopy() *ALMGitLabSpec {
	if in == nil {
		return nil
	}
	out := new(ALMGitLabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALMGitLabStatus) DeepCopyInto(out *ALMGitLabStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALMGitLabStatus.
func (in *ALMGitLabStatus) DeepCopy() *ALMGitLabStatus {
	if in == nil {
		return nil
	}
	out := new(ALMGitLabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webhook) DeepCopyInto(out *Webhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webhook.
func (in *Webhook) DeepCopy() *Webhook {
	if in == nil {
		return nil
	}
	out := new(Webhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Webhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookList) DeepCopyInto(out *WebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Webhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookList.
func (in *WebhookList) DeepCopy() *WebhookList {
	if in == nil {
		return nil
	}
	out := new(WebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookObservation) DeepCopyInto(out *WebhookObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookObservation.
func (in *WebhookObservation) DeepCopy() *WebhookObservation {
	if in == nil {
		return nil
	}
	out := new(WebhookObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookParameters) DeepCopyInto(out *WebhookParameters) {
	*out = *in
	if in.ProjectKey != nil {
		in, out := &in.ProjectKey, &out.ProjectKey
		*out = new(string)
		**out = **in
	}
	if in.ProjectKeyRef != nil {
		in, out := &in.ProjectKeyRef, &out.ProjectKeyRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectKeySelector != nil {
		in, out := &in.ProjectKeySelector, &out.ProjectKeySelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v2.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookParameters.
func (in *WebhookParameters) DeepCopy() *WebhookParameters {
	if in == nil {
		return nil
	}
	out := new(WebhookParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSpec) DeepCopyInto(out *WebhookSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSpec.
func (in *WebhookSpec) DeepCopy() *WebhookSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookStatus) DeepCopyInto(out *WebhookStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookStatus.
func (in *WebhookStatus) DeepCopy() *WebhookStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookStatus)
	in.DeepCopyInto(out)
	return out
}
