//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGate) DeepCopyInto(out *QualityGate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGate.
func (in *QualityGate) DeepCopy() *QualityGate {
	if in == nil {
		return nil
	}
	out := new(QualityGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QualityGate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateConditionObservation) DeepCopyInto(out *QualityGateConditionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateConditionObservation.
func (in *QualityGateConditionObservation) DeepCopy() *QualityGateConditionObservation {
	if in == nil {
		return nil
	}
	out := new(QualityGateConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateConditionParameters) DeepCopyInto(out *QualityGateConditionParameters) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Op != nil {
		in, out := &in.Op, &out.Op
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateConditionParameters.
func (in *QualityGateConditionParameters) DeepCopy() *QualityGateConditionParameters {
	if in == nil {
		return nil
	}
	out := new(QualityGateConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateList) DeepCopyInto(out *QualityGateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QualityGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateList.
func (in *QualityGateList) DeepCopy() *QualityGateList {
	if in == nil {
		return nil
	}
	out := new(QualityGateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QualityGateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateObservation) DeepCopyInto(out *QualityGateObservation) {
	*out = *in
	out.Actions = in.Actions
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]QualityGateConditionObservation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateObservation.
func (in *QualityGateObservation) DeepCopy() *QualityGateObservation {
	if in == nil {
		return nil
	}
	out := new(QualityGateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateParameters) DeepCopyInto(out *QualityGateParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]QualityGateConditionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateParameters.
func (in *QualityGateParameters) DeepCopy() *QualityGateParameters {
	if in == nil {
		return nil
	}
	out := new(QualityGateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateSpec) DeepCopyInto(out *QualityGateSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateSpec.
func (in *QualityGateSpec) DeepCopy() *QualityGateSpec {
	if in == nil {
		return nil
	}
	out := new(QualityGateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGateStatus) DeepCopyInto(out *QualityGateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGateStatus.
func (in *QualityGateStatus) DeepCopy() *QualityGateStatus {
	if in == nil {
		return nil
	}
	out := new(QualityGateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityGatesActions) DeepCopyInto(out *QualityGatesActions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityGatesActions.
func (in *QualityGatesActions) DeepCopy() *QualityGatesActions {
	if in == nil {
		return nil
	}
	out := new(QualityGatesActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfile) DeepCopyInto(out *QualityProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfile.
func (in *QualityProfile) DeepCopy() *QualityProfile {
	if in == nil {
		return nil
	}
	out := new(QualityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QualityProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileList) DeepCopyInto(out *QualityProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QualityProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileList.
func (in *QualityProfileList) DeepCopy() *QualityProfileList {
	if in == nil {
		return nil
	}
	out := new(QualityProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QualityProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileObservation) DeepCopyInto(out *QualityProfileObservation) {
	*out = *in
	if in.LastUsed != nil {
		in, out := &in.LastUsed, &out.LastUsed
		*out = (*in).DeepCopy()
	}
	if in.RulesUpdatedAt != nil {
		in, out := &in.RulesUpdatedAt, &out.RulesUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]QualityProfileRuleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileObservation.
func (in *QualityProfileObservation) DeepCopy() *QualityProfileObservation {
	if in == nil {
		return nil
	}
	out := new(QualityProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileParameters) DeepCopyInto(out *QualityProfileParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(bool)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]QualityProfileRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileParameters.
func (in *QualityProfileParameters) DeepCopy() *QualityProfileParameters {
	if in == nil {
		return nil
	}
	out := new(QualityProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleDescription) DeepCopyInto(out *QualityProfileRuleDescription) {
	*out = *in
	out.Context = in.Context
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleDescription.
func (in *QualityProfileRuleDescription) DeepCopy() *QualityProfileRuleDescription {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleDescriptionSectionsContext) DeepCopyInto(out *QualityProfileRuleDescriptionSectionsContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleDescriptionSectionsContext.
func (in *QualityProfileRuleDescriptionSectionsContext) DeepCopy() *QualityProfileRuleDescriptionSectionsContext {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleDescriptionSectionsContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleImpact) DeepCopyInto(out *QualityProfileRuleImpact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleImpact.
func (in *QualityProfileRuleImpact) DeepCopy() *QualityProfileRuleImpact {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleImpact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleObservation) DeepCopyInto(out *QualityProfileRuleObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SysTags != nil {
		in, out := &in.SysTags, &out.SysTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Impacts != nil {
		in, out := &in.Impacts, &out.Impacts
		*out = make([]QualityProfileRuleImpact, len(*in))
		copy(*out, *in)
	}
	if in.DescriptionSections != nil {
		in, out := &in.DescriptionSections, &out.DescriptionSections
		*out = make([]QualityProfileRuleDescription, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]QualityProfileRuleParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleObservation.
func (in *QualityProfileRuleObservation) DeepCopy() *QualityProfileRuleObservation {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleParameter) DeepCopyInto(out *QualityProfileRuleParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleParameter.
func (in *QualityProfileRuleParameter) DeepCopy() *QualityProfileRuleParameter {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileRuleParameters) DeepCopyInto(out *QualityProfileRuleParameters) {
	*out = *in
	if in.Impacts != nil {
		in, out := &in.Impacts, &out.Impacts
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.Prioritized != nil {
		in, out := &in.Prioritized, &out.Prioritized
		*out = new(bool)
		**out = **in
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileRuleParameters.
func (in *QualityProfileRuleParameters) DeepCopy() *QualityProfileRuleParameters {
	if in == nil {
		return nil
	}
	out := new(QualityProfileRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileSpec) DeepCopyInto(out *QualityProfileSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileSpec.
func (in *QualityProfileSpec) DeepCopy() *QualityProfileSpec {
	if in == nil {
		return nil
	}
	out := new(QualityProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualityProfileStatus) DeepCopyInto(out *QualityProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualityProfileStatus.
func (in *QualityProfileStatus) DeepCopy() *QualityProfileStatus {
	if in == nil {
		return nil
	}
	out := new(QualityProfileStatus)
	in.DeepCopyInto(out)
	return out
}
