// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this QualityProfile.
func (mg *QualityProfile) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Rules); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Rules[i3].Rule),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Rules[i3].RuleRef,
			Selector:     mg.Spec.ForProvider.Rules[i3].RuleSelector,
			To: reference.To{
				List:    &RuleList{},
				Managed: &Rule{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Rules[i3].Rule")
		}
		mg.Spec.ForProvider.Rules[i3].Rule = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Rules[i3].RuleRef = rsp.ResolvedReference

	}

	return nil
}
